### ISSUE TITLE
Cannot find path Extract-Archive

### ISSUE THREAD

**Issue by remcovn** [printix/Power-BI#3]
Today I tried configuring the Power BI dashboard. The powershell runbook outputs some warnings that – I think – causes the dashboard to fail loading the data.

It looks like the script is unable to extract the ‘tracking_data’ and ‘device_readings’ zip-files. Maybe it has something to do with the underscores?

I removed some ‘supresserrors’ arguments and this is the exception I get when running the script:

Exception: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\Client\Temp\TRACKING_DATA\TRACKING_DATA.json' because it does not exist. at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context) at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance) at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance) at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance) at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, CmdletProviderContext context) at Microsoft.PowerShell.Commands.GetItemCommand.ProcessRecord() Activity: Get-Item Error Category: ObjectNotFound Error Reason: ItemNotFoundException ( Exception: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\Client\Temp\TRACKING_DATA\TRACKING_DATA.json' because it does not exist. at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNo

**Comment by MortenRei** [comment]
It could be because there is no data inside of the files (You dont actually have any Printix jobs within the time frame specific). Which runbook are you running? The one for partners or the one for direct customers?

What is the exact output of the warning?

**Comment by remcovn** [comment]
When I open the .zip file the script downloads to the Azure Blob Storage it contains data so that isn't causing the problem.

The runbook I'm using is Get-PrintixPartnerDataExtract so the one for partners.

```
08:26:44 - Successfuly connected to Azure with Service Principal.
08:26:44 - Getting AutomationPSCredential [PrintixClientCredentials].
08:26:44 - Printix API entry [https://api.printix.net/public/partners/xxxxx-xxxx-xxxx-xxxx-xxxxxxx].
08:26:47 - Working on Partner account [Proxsys] email [xxxx@proxsys.nl]
08:26:47 - Found [1] tenants
08:26:47 - After filtering out tenants not found in storagemapping, continuing to work on [1] tenants
08:26:47 - Working on tenant [proxsysnl] tenantdomain [proxsysnl.printix.net]
08:26:47 -   Requesting data extract. This might take some time...
08:27:49 -     Getting Azure Storage account [prox3printixstorage] in Resource group [prox3printix]
08:27:50 -     Getting Azure Storage container [433f2bfd-6420-4730-9f74-2256a35afbd7] 
08:27:50 -     Getting Azure Storage account [prox3printixstorage] in Resource group [prox3printix]
08:27:51 -     Getting Azure Storage container [proxsysnl-production] 
08:27:51 -         Getting Azure Storage Blob Content from cludblob [users.zip]
08:27:52 -             Unzipping file [C:\Users\Client\Temp\USERS.zip]
08:27:53 -             Changing encoding to [UTF8]
08:27:53 -             Uploading file to container [proxsysnl-production]
08:27:53 -         Getting Azure Storage Blob Content from cludblob [tracking-data.zip]
08:27:53 -             Unzipping file [C:\Users\Client\Temp\TRACKING_DATA.zip]
08:27:53 -              [TRACKING_DATA] does not seem to have any content. Skipping file
08:27:54 -         Getting Azure Storage Blob Content from cludblob [networks.zip]
08:27:54 -             Unzipping file [C:\Users\Client\Temp\NETWORKS.zip]
08:27:54 -             Changing encoding to [UTF8]
08:27:54 -             Uploading file to container [proxsysnl-production]
08:27:54 -         Getting Azure Storage Blob Content from cludblob [workstations.zip]
08:27:54 -             Unzipping file [C:\Users\Client\Temp\WORKSTATIONS.zip]
08:27:54 -             Changing encoding to [UTF8]
08:27:54 -             Uploading file to container [proxsysnl-production]
08:27:54 -         Getting Azure Storage Blob Content from cludblob [printers.zip]
08:27:54 -             Unzipping file [C:\Users\Client\Temp\PRINTERS.zip]
08:27:55 -             Changing encoding to [UTF8]
08:27:55 -             Uploading file to container [proxsysnl-production]
08:27:55 -         Getting Azure Storage Blob Content from cludblob [jobs.zip]
08:27:55 -             Unzipping file [C:\Users\Client\Temp\JOBS.zip]
08:27:55 -             Changing encoding to [UTF8]
08:27:55 -             Uploading file to container [proxsysnl-production]
08:27:55 -         Getting Azure Storage Blob Content from cludblob [device-readings.zip]
08:27:55 -             Unzipping file [C:\Users\Client\Temp\DEVICE_READINGS.zip]
08:27:55 -              [DEVICE_READINGS] does not seem to have any content. Skipping file
08:27:55 - Successfully extracted data for tenant [proxsysnl]
08:27:55 - Successfully extracted data for all tenants.

```

So the specific warning messages are:

08:27:53 -              [TRACKING_DATA] does not seem to have any content. Skipping file
08:27:55 -              [DEVICE_READINGS] does not seem to have any content. Skipping file

**Comment by remcovn** [comment]
Hi Morten, apologies for the delayed reply. I checked the zip-file that gets downloaded. Within this zip-file both the TRACKING_DATA and DEVICE_READINGS files are available and do have content. The actual content of, for example TRACKING_DATA, is as follows:

```
[
{"tenantId":"553b605c-27eb-43f3-a129-c160e6d359d8","jobId":"9857621c-ed5f-43af-9ba6-f82dc5d1aa16","trackingId":"177e1955-3167-48b5-bec8-94e178a38389","cloudReceived":"2018-06-14T11:54:04.642Z","mode":"NOW","printerId":"a48b1440-8302-4e77-80fa-f1a0b6e30111","printTime":"2018-06-14T11:54:04.629Z","paperSize":"A4","duplex":true,"color":false,"pageCount":3,"pageCountStatus":"SW_COUNT","printJobStatus":"PRINT_OK"},
{"tenantId":"553b605c-27eb-43f3-a129-c160e6d359d8","jobId":"a3843d67-cd2c-4c90-8bf9-69fb7b6c3ef1","trackingId":"efd7c53b-afab-47dd-8569-c1721f89fb07","cloudReceived":"2018-06-14T11:54:10.397Z","mode":"NOW","printerId":"a48b1440-8302-4e77-80fa-f1a0b6e30111","printTime":"2018-06-14T11:54:10.389Z","paperSize":"A4","duplex":true,"color":true,"pageCount":1,"pageCountStatus":"SW_COUNT","printJobStatus":"PRINT_OK"},
{"tenantId":"553b605c-27eb-43f3-a129-c160e6d359d8","jobId":"88cdfeea-098e-459e-8314-6a373bb36e39","trackingId":"e3267ff0-c786-4999-b700-568db6328a09","cloudReceived":"2018-06-14T11:55:22.683Z","mode":"NOW","printerId":"a48b1440-8302-4e77-80fa-f1a0b6e30111","printTime":"2018-06-14T11:55:22.670Z","paperSize":"A4","duplex":true,"color":true,"pageCount":11,"pageCountStatus":"SW_COUNT","printJobStatus":"PRINT_OK"},
...
...
...
```

The error message that Powershell returns is the following:

`
Exception: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\Client\Temp\TRACKING_DATA\TRACKING_DATA.json' because it does not exist.
 at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
 at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
 at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
 at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider, CmdletProvider& providerInstance)
 at System.Management.Automation.SessionStateInternal.GetItem(String[] paths, CmdletProviderContext context)
 at Microsoft.PowerShell.Commands.GetItemCommand.ProcessRecord() Activity: Get-Item Error Category: ObjectNotFound Error Reason: ItemNotFoundException ( Exception: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\Client\Temp\TRACKING_DATA\TRACKING_DATA.json' because it does not exist.
 at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNo
`

**Comment by MortenRei** [comment]
I think #2 introduced the bug. Basically it happens because I changed an foreach logic from;

`
Foreach ($CloudBlobContainer in $StorageContainerPrintixExtract.CloudBlobContainer.ListBlobs()) `

to

`Foreach ($ExtractType in $ExtractResults.ExtractStatus.extractStatuses.type)`

This was supposed to be a minor change that allowed for the removal of a lot of duplicate code. This lead to capital letters in some of the files and a mismatch between - and _. I must have missed something in the testing before releasing the new version. I'll improve the code ASAP and release a fix for the bug that was introduced.

**Comment by MortenRei** [comment]
@remcovn and @PatrickMorandi could you please update the automation runbook code you have been using with the latest code and do a new test? The latest commit should have fixed the issue.

**Comment by PatrickMorandi** [comment]
Hi Morten
I tried today the new  Get-PrintixDirectCustomerDataExtract.ps1 

Now we get the following output:

12:45:15 - Successfuly connected to Azure with Service Principal.
12:45:16 - Getting AutomationPSCredential [PrintixAPICredentials].
12:45:19 -   Requesting data extract. This might take some time...
13:09:23 - **ExtractstatusCounter is greather than 120. Data extract might be uncomplete!**
13:09:23 - Unable to get a successfull extract. Error: @{started=2018-09-04T12:45:21.005Z; completed=; 
extractStatuses=System.Object[]; expires=2018-09-05T12:45:21.077Z; container=0c7375e3-c616-4219-a495-a0a0c85fd55c; 
params=; _links=}
13:09:23 - Successfully extracted data.

And we have  just 5 zip files  jobs.zip, networks.zip, tracking-data.zip, users.zip, workstations.zip

**Comment by MortenRei** [comment]
Hi @PatrickMorandi 

There was an temporary problem with the Printix API it self, it should now be resolved by Printix. Please try again and see if everything is resolved.

**Comment by PatrickMorandi** [comment]
Hi Morten

I tried again. I made a export for the last 89 Days and it worked.

Please remember the lower / upercase stuff.

Regards
Patrick

**Comment by remcovn** [comment]
The script is running fine at my end as well! Thanks!
________________________________
